title: Eric Lu
description: "Tech Guru, Full-stack Developer, Node.js Lover"

url: http://www.ericluwj.com
baseurl: ""
paginate_path: "page:num/"

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about.html
 - title: Contact
   url: /contact.html

social:
   github: ericluwj
   twitter: ericluwj
   facebook: ericluwj
   email: ericluwj@hotmail.com

google_analytics: "UA-69072942-1"

gems:
 - jekyll-paginate
 - jekyll-feed
 - jekyll-sitemap
 - jekyll-redirect-from